name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      id: build
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
      env:
        FILE_OUTPUT_DIR: ${{ steps.build.outputs.FILE_OUTPUT_DIR }}

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{env.FILE_OUTPUT_DIR}}
        release_name: Release v${{env.FILE_OUTPUT_DIR}}
        body: |
          Release v${{env.FILE_OUTPUT_DIR}}
        draft: false
        prerelease: false
      
    - name: Upload Chromium Files
      id: upload_chromium_files
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./versions/tbc2_${{env.FILE_OUTPUT_DIR}}-chromium.zip
        asset_name: tbc2_${{env.FILE_OUTPUT_DIR}}-chromium.zip
        asset_content_type: application/zip

    - name: Upload Firefox Files
      id: upload_firefox_files
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./versions/tbc2_${{env.FILE_OUTPUT_DIR}}-firefox.zip
        asset_name: tbc2_${{env.FILE_OUTPUT_DIR}}-firefox.zip
        asset_content_type: application/zip
